package com.feelsokman.analytics

enum class TrackingEvents {
    ABOUT, SHARE, UPVOTE, DOWNVOTE, DOWNLOAD, TUTORIAL, THEME_CHANGE,
    STORE_PERM_DENIED, RATING_REDIRECT, STOP_ALL_SOUNDS, MAX_GIFS, SOUND_CHOICE,
    SAVE_FAIL, SETTINGS_PERM_FAIL, AUDIO_PERM_FAIL, AUDIO_PERM_NEVER_ASK, PERM_DIALOG_FAIL,
    SHARE_APP_LINK, CREDITS, PRIVACY_POLICY, DEV_PAGE_REDIRECT, SHOW_SONG_SELECTION,
    NO_SONGS_ERROR, SONG_OPTIONS, OPTIONS_FRAG, SOUND, CLEAN_SCREEN, MAIN_MUSIC_TOGGLE,
    CHANGE_MUSIC, RINGTONE, NOTIFICATION, UPDATE_MAX_GIFS, BOTTOM_SHEET_HINT,
    ERROR_RINGTONE, ERROR_NOTIFICATION, SHARE_GIF, TUTORIAL_GANG, COPY_TO_CLIP, EXCEPTION, FAV_CHOICE_DIALOG, FAVOURITE,
    TAB_ALL, TAB_FAVOURITES, TAB_SEARCH, SAVE_SOUND
}